
from enum import Enum

class PositionStatus(Enum):
    FILLED = "FILLED"
    CANCELED = "CANCELED"
    INVALID = "INVALID"
    PARTIALLY_FILLED = "PARTIALLY_FILLED"
    PARTIAL = "PARTIAL"
    PARTIALLY_CANCELED_AND_PENDING = "PARTIALLY_CANCELED_AND_PENDING"
    INVALID_TICKET_COUNT = "INVALID_TICKET_COUNT"
    NONE = "NONE"
    OPENED = "OPENED"
    SUBMITTED = "SUBMITTED"
    CLOSED = "CLOSED"
    CLOSE_SUBMITTED = "CLOSE_SUBMITTED"
